env: "local"
grpc_server:
  host: "localhost"
  port: "50058"
order_db:
  dsn: "host=localhost user=postgres password=admin dbname=shvark_order_service port=5432 sslmode=disable"
log_config:
  log_level: "debug"
  log_format: "json"
  log_output: "stdout"
banking-service:
  host: "localhost"
  port: "50057"
wallet-service:
  host: "localhost"
  port: "3000"
kafka-service:
  host: "localhost"
  port: "9092"
  username: ""
  password: ""
  mechanism: ""
  tls_enabled: true